### ISSUE TITLE
Setup docstrings and Documenter.jl

### ISSUE THREAD

**Issue by orlox** [Jems-jl/Jems.jl#1]
We need to implement proper docstrings across the code in a way that is compatible with Documenter.jl, and make use of Documenter.jl in our code. Given that we are using a monorepo, with multiple packages included, we should make a single deployment of Documenter.jl that includes all of them. Here is a description on the workflow to do that:

https://documenter.juliadocs.org/dev/man/hosting/#Deploying-from-a-monorepo

**Comment by matthiasfabry** [comment]
This is mostly done with #18 and #19
